config/routes.rb
JeffreyDill::Application.routes.draw do

  root 'static_pages#index'

  resources :professional_pages

  resources :personal_pages

  resources :home_pages

  resources :blog

  resources :tweets

  get '/blog', :to => 'blog#index', :as => 'blogs'

  resources :testing

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	def helper_string
		# "#{self.title}  --  #{self.article}  --  #{self.date}"
		self.title + "  --  " + self.article + "  --  " + self.date.to_s
	end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	before_filter :authenticate, :except => [:index, :show]

	def create
		@blog = Blog.create( blog_params )

		if @blog.valid?
			redirect_to blog_index_path
		else
			render :new, :status => :unprocessable_entity
		end
	end

	def destroy
		Blog.destroy(params[:id])
		redirect_to blog_index_path
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])

		@blog.update_attributes( blog_params )

		if @blog.valid?
			redirect_to blog_index_path
		else
			render :edit, :status => :unprocessable_entity
		end
	end

	def new
		@blog = Blog.new
	end

	def index
		@blogs = Blog.all.order('created_at DESC')
	end

	def show
		@blog = Blog.find(params[:id])
	end

	private
	def blog_params
		params.require(:blog).permit(:title, :article, :date)
	end

	private
	def authenticate
		authenticate_or_request_with_http_basic do |name, password|
			name == "admin" && password == "admin"
		end
	end
end	

app/controllers/personal_pages_controller.rb
class PersonalPagesController < ApplicationController
	def index

	end
end

app/controllers/professional_pages_controller.rb
class ProfessionalPagesController < ApplicationController
	def index

	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index

	end
end

app/controllers/testing_controller.rb
class TestingController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def index
		@tweets = Twitter.user_timeline(:count => 200, :include_entities => true)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Jeffrey Dill"

		if page_title.empty?
			base_title
		else
			"#{base_title}  |  #{page_title}"
		end
	end
end

app/helpers/blog_helper.rb
module BlogHelper
	def recent_blog_posts_cache_key
		"recent-blogs-#{Blog.count}"
	end
end

app/helpers/personal_pages_helper.rb
module PersonalPagesHelper
end

app/helpers/professional_pages_helper.rb
module ProfessionalPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/testing_helper.rb
module TestingHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def tweet_text(tweet)
		hshParsedTweet = tweet_hash(tweet)
		strTweetParsedText = hshParsedTweet['text']
		strTweetModifiedTextPass1 = ""
		strTweetModifiedTextPass2 = ""
		strTweetUser = ""
		strTweetHashtag = ""
		iCharCount = 0
		iTweetLength = strTweetParsedText.length
		bolUserFound = false
		bolHashtagFound = false
		strUserColor = "#267DC0"
		strHashtagColor = "#208345"
		strURLColor = "#208345"
		strUserLinkRoot = "<a class='grow' href='http://www.twitter.com/|USER|' target='_blank'><span style='color: #{strUserColor};'>|USER|</span></a>"
		strHashtagLinkRoot = "<a class='grow' href='http://www.twitter.com/search?q=%23|HASHTAG|&src=hash' target='_blank'><span style='color: #{strHashtagColor};'>#|HASHTAG|</span></a>"
		strURLLinkRoot = "<a class='grow' href='|URL|' target='_blank'><span style='color: |URL_COLOR|;'>|URL|</span></a>"
		iURLStartIndex = 0
		iURLEndIndex = 0
		strParsedURL = ""

		strTweetModifiedTextPass1 = strTweetParsedText.gsub(/[[:space:]]/, " ")

		while true do
			iURLStartIndex = strTweetModifiedTextPass1.index("http", iURLEndIndex)

			if (iURLStartIndex == nil) then
				break
			end

			iURLEndIndex = strTweetModifiedTextPass1.index(" ", iURLStartIndex)

			if (iURLEndIndex == nil) then
				iURLEndIndex = iTweetLength
			end

			strParsedURL = strTweetModifiedTextPass1[iURLStartIndex..iURLEndIndex]
			strModifiedURL = strURLLinkRoot.gsub("|URL|", strParsedURL)
			strTweetModifiedTextPass1.sub!(strParsedURL, strModifiedURL)

			iURLReplacementLength = strModifiedURL.length
			iURLEndIndex = iURLStartIndex + iURLReplacementLength
			iTweetLength = strTweetModifiedTextPass1.length
		end

		strTweetModifiedTextPass1.each_char do |char|
			iCharCount += 1

			if (char == "@" || bolUserFound) then
				bolUserFound = true

				if (!valid_user_or_hashtag_character(char)) then
					strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + strUserLinkRoot.gsub("|USER|", strTweetUser)
					strTweetUser = ""
					bolUserFound = false

					strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + char
				else
					strTweetUser = strTweetUser + char

					if (iCharCount == iTweetLength) then
						strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + strUserLinkRoot.gsub("|USER|", strTweetUser)
					end
				end
			elsif (char == "#" || bolHashtagFound) then
				bolHashtagFound = true

				if (!valid_user_or_hashtag_character(char)) then
					strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + strHashtagLinkRoot.gsub("|HASHTAG|", strTweetHashtag.sub("#", ""))
					strTweetHashtag = ""
					bolHashtagFound = false

					strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + char
				else
					strTweetHashtag = strTweetHashtag + char

					if (iCharCount == iTweetLength) then
						strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + strHashtagLinkRoot.gsub("|HASHTAG|", strTweetHashtag.sub("#", ""))
					end
				end
			else
				strTweetModifiedTextPass2 = strTweetModifiedTextPass2 + char
			end
		end

		strTweetModifiedTextPass2.sub!("|URL_COLOR|", strUserColor)

		strTweetModifiedTextPass2.html_safe
	end

	def valid_user_or_hashtag_character(char)
		valid = 
		case char.bytes[0]
			when 48..57
				true
			when 64..90
				true
			when 97..122
				true
			when 35
				true
			when 95
				true
			else
				false
		end
	end

	def tweet_url(tweet)
		hshParsedTweet = tweet_hash(tweet)

		if ((defined? hshParsedTweet['entities']['media'][0]['media_url_https']) == nil) then
			nil
		else
			hshParsedTweet['entities']['media'][0]['media_url_https']
		end
	end

	def tweet_id(tweet)
		tweet_hash(tweet)['id']
	end

	def tweet_hash(tweet)
		hshParsedTweet = JSON.parse(tweet.to_json)
	end
end

app/views/blog/_form.html.erb
<span class="styled-paragraph">
	<%= simple_form_for @blog do |f| %>
		<%= f.input :title, :label => 'Title:', :placeholder => "What's the title of this post?" %>

		<br/>

		<%= f.input :article, :label => 'Article:', :placeholder => "What's on your mind?" %>

		<br/>

		<%= f.input :date, :label => 'Date:', :placeholder => '1900-01-30' %>

		<br/>

		<%= submit_tag 'Save', :class => 'btn btn-success btn-large' %>
	<% end %>
</span>

app/views/blog/edit.html.erb
<div class="section-background text-center">
	<div class="styled-h2">
		Update The Blog
	</div>
	
	<%= render :partial => 'form' %>
</div>

app/views/blog/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, 'Blog') %>
	</head>

	<%= link_to 'Create New Blog', new_blog_path, :class => 'btn btn-success btn-large' %>

	<% @blogs.each do |blog| %>
		<%= link_to blog_path(blog) do %>
			<div class="blog-section-background text-center">
				<div class="blog-header-background">
					<div class="blog-preview-title">
						<%= blog.title %>
					</div>
				</div>

				<div class="blog-preview-date">
					<%= blog.date.strftime("%A, %B %d, %Y") %>
				</div>

				<div class="blog-preview-article">
					<%= blog.article[0,150] + " [...]" %>
				</div>
			</div>
		<% end %>
	<% end %>
</html>

app/views/blog/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, "New Blog") %>
	</head>

	<div class="section-background text-center">
		<div class="styled-h2">
			Create The Blog
		</div>
		
		<%= render :partial => 'form' %>
	</div>
</html>

app/views/blog/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, @blog.title) %>
	</head>

	<div class="section-background text-center">
		<div class="blog-title">
			<%= @blog.title %>
		</div>

		<div class="blog-date">
			<%= @blog.date.strftime("%A, %B %d, %Y") %>
		</div>

		<div class="blog-article">
			<%= simple_format(@blog.article) %>
		</div>

		<%= link_to 'Back', blogs_path, :class => 'btn btn-success btn-large' %>
		<%= link_to 'Delete', blog_path(@blog), :method => :delete, :class => 'btn btn-large btn-danger', :confirm => 'You sure you want to delete this?' %>
		<%= link_to 'Edit', edit_blog_path(@blog), :class => 'btn btn-large btn-warning' %>
	</div>
</html>

app/views/layouts/_footer.html.erb
<br/><br/><br/>

<footer class="footer">
		<%= link_to image_tag("social-media/twitter-48-white.png"), "http://www.twitter.com/jeffdill2", :target => "#", :class => 'social-media-link float' %>

		<%= link_to image_tag("social-media/linkedin-48-white.png"), "http://www.linkedin.com/profile/view?id=59054351", :target => "#", :class => 'social-media-link float' %>

		<%= link_to image_tag("social-media/github-48-white.png"), "https://www.github.com/jeffdill2", :target => "#", :class => 'social-media-link float' %>

		<%= link_to image_tag("social-media/vimeo-48-white.png"), "https://www.vimeo.com/jeffdill2", :target => "#", :class => 'social-media-link float' %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-header navbar-fixed-top" style="position: fixed; ">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div style="margin-top: -3px; ">
        <%= link_to '<span style="font-size: 30px; ">[</span>JEFFREY.DILL<span style="font-size: 30px; ">]</span>'.html_safe, root_path, :class => 'brand' %>
      </div>

      <div class="nav-collapse collapse">
        <ul class="nav" style="margin-top: 4px; ">
          <li>
            <%= link_to ':THE_PERSONAL', personal_pages_path %>
          </li>

          <li>
            <%= link_to ':THE_PROFESSIONAL', professional_pages_path %>
          </li>

          <li>
            <%= link_to ':THE_SOCIAL', tweets_path %>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle" id="recent_blog_posts" role="button" data-toggle="dropdown" data-target="#" href="/blog">
              :THE_EDITORIAL
              <b class="caret"></b>
            </a>

            <ul class="dropdown-menu styled-paragraph" role="menu" aria-labelledby="recent_blog_posts">
              <li>
                <%= link_to 'View All Posts', blogs_path %>
              </li>

              <li style="margin-left: 20px; padding-top: 10px; padding-bottom: 5px; ">
                Recent Posts...
              </li>

              <% cache(recent_blog_posts_cache_key) do %>
                <% Blog.order('created_at DESC').limit(5).each do |blog| %>
                  <li role="presentation" style="margin-left: 10px; ">
                    <%= link_to blog.title, blog, role: 'menuitem', tabindex: '-1' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--//////////////////////////////////////////////
    /////////////////////////////// DYNAMIC PAGE TITLE
    ///////////////////////////////////////////////-->
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    
    <!--//////////////////////////////////////////////
    ///////// JS, WEB FONTS, AND APPLICATION RESOURCES
    ///////////////////////////////////////////////-->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <link href='http://fonts.googleapis.com/css?family=Monofett|Inconsolata:400,700|Ubuntu+Mono|Nixie+One' rel='stylesheet' type='text/css'>

    <script type="text/javascript">
      $('.dropdown-toggle').dropdown()
    </script>
  </head>

  <body>
    <!--//////////////////////////////////////////////
    //////////////////////////////////// YIELDING PAGE
    ///////////////////////////////////////////////-->
    <div class="wrapper">
      <%= render :partial => 'layouts/header' %>
      
      <div class="container" style="padding-top: 70px; ">
        <%= yield %>
      </div>

      <%= render :partial => 'layouts/footer' %>
    </div>

    <!--//////////////////////////////////////////////
    ///////////////////////////////// GOOGLE ANALYTICS
    ///////////////////////////////////////////////-->
    <% unless Rails.env.development? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-46472596-1', 'jeffreydill.com');
        ga('send', 'pageview');
      </script>
    <% end %>
  </body>
</html>

app/views/personal_pages/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, 'Personal') %>
	</head>
	
	<body>
		<div class="section-background">
			<div class="header-background">
				<h2 class="styled-h2">
					About Me
				</h2>
			</div>

			<div class="styled-paragraph">
				<br/>
				<br/>
				Hi! My name is Jeffrey Dill and this is my personal website.
				</br></br>
				I'm a native of Greenville, SC a graduate of Clemson University, husband to a wonderful wife, and a son of God redeemed by His grace.
				<br/><br/>
				I love travelling and experiencing the world as it presents itself to me. I've lived in Charlotte, NC, Pittsburgh, PA, and am now living back in Greenville, SC.
				</br></br>
				Please feel free to <a href="mailto:jeffdill2@gmail.com?subject=Hello!">reach out to me</a> about job opportunities or just to say HELLO!
			</div>

			<!--
			<div style="margin-left: 20px; ">
				<%#= link_to "Let's Get Professional...", professional_pages_path, :class => "btn btn-info btn-medium styled-button" %>
			</div>
			-->
		</div>

		<div class="section-background">
			<div class="header-background">
				<h2 class="styled-h2">
					My Interests
				</h2>
			</div>

			<div class="styled-paragraph">
				<br/>
				<br/>

				<ul>
					<li>Arduino</li>
					<li>Disc Golf</li>
					<li>Travelling</li>
					<li>Hiking</li>
					<li>Camping</li>
					<li>Cycling</li>
					<li>Music</li>
					<li>Vinyl Records</li>
				</ul>
			</div>
		</div>
	</body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, 'Home') %>
	</head>
	
	<div class="opaque-grey-box text-center">
		<h1 class="styled-h1">
			WELCOME
		</h1>

		<h2 class="styled-h2">
			to
		</h2>

		<h2 class="styled-h1">
			THE #1 JEFFREY DILL RELATED NEWS SOURCE!
		</h2>

		<br />
		<br />

		<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large styled-button' %>

		<br/>
		<br/>
	</div>
</html>

app/views/testing/index.html.erb
<!--

PEOPLE TO MENTION FOR SHOUTOUTS:
http://ryanfait.com/sticky-footer/
http://designshack.net/articles/css/infinitephotobanner/

-->

<!DOCTYPE html>
<html>
	<head>
		<script>
			/*
			////////////////////////////////////////////////////////////
			/////////////////////////////////////////// AJAX EXPERIMENTS
			////////////////////////////////////////////////////////////
			*/
			function loadXMLDoc()
			{
				//alert("loadXMLDoc running.");

				var xmlhttp;

				if (window.XMLHttpRequest)
		  		{
		  			xmlhttp = new XMLHttpRequest();
		  		}
				else
		  		{
		  			xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
		  		}
				
				xmlhttp.onreadystatechange = function()
		  		{
		  			//alert(xmlhttp.readyState + " - " + xmlhttp.status);

		  			if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
		    		{
		    			//alert("AJAX call successful");
		    			document.getElementById("divAboutMe").innerHTML = xmlhttp.responseText;
		    		}
				}
				
				xmlhttp.overrideMimeType('text/plain');
				xmlhttp.open("GET", "http://www.mozilla.org/", false);
				xmlhttp.send();
			}

			/*
			////////////////////////////////////////////////////////////
			//////////////////////////////////////// TWITTER FEED WIDGET
			////////////////////////////////////////////////////////////
			*/
			!function(d,s,id)
			{
				var js, fjs = d.getElementsByTagName(s)[0];
				var p = /^http:/.test(d.location)?'http':'https';

				if(!d.getElementById(id))
				{
					js = d.createElement(s);
					js.id = id;
					js.src = p+"://platform.twitter.com/widgets.js";
					fjs.parentNode.insertBefore(js,fjs);
				}
			}
			(document,"script","twitter-wjs");
		</script>
	</head>

	<body>
		<!--////////////////////////////////////////////////////////
		//////////////////////////////////////// TWITTER FEED WIDGET
		/////////////////////////////////////////////////////////-->
		<a class="twitter-timeline" href="https://twitter.com/jeffdill2" data-widget-id="447911320210251776">
			Tweets by @jeffdill2
		</a>

		<!--////////////////////////////////////////////////////////
		///////////////////////////////////// SCROLLING PHOTO BANNER
		/////////////////////////////////////////////////////////-->
		<div id="container">
		    <div class="photobanner">
		        <%= image_tag "CNN_Award.png", :class => "first", :width => "233px", :height => "350px" %>
		        <%= image_tag "Fox_News_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "NYT_Award.png", :width => "233px", :height => "350px" %>
				<%= image_tag "CNN_Award.png", :width => "233px", :height => "350px" %>
				<%= image_tag "Fox_News_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "NYT_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "CNN_Award.png", :width => "233px", :height => "350px" %>
				<%= image_tag "Fox_News_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "NYT_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "CNN_Award.png", :width => "233px", :height => "350px" %>
				<%= image_tag "Fox_News_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "NYT_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "CNN_Award.png", :width => "233px", :height => "350px" %>
				<%= image_tag "Fox_News_Award.png", :width => "233px", :height => "350px" %>
		        <%= image_tag "NYT_Award.png", :width => "233px", :height => "350px" %>
		    </div>
		</div>

		<!--////////////////////////////////////////////////////////
		//// SCROLLING PHOTO BANNER (TESTING - DIV INSTEAD OF IMAGE)
		/////////////////////////////////////////////////////////-->
		<div id="container">
		    <div class="photobanner">
		        <div class="transparent-soft-blue-box text-center first" style="width: 466px; height: 350px; ">
					<h1 class="styled-h1">
						Welcome!
					</h1>

					<h2 class="styled-h2">
						Your #1 source for all things Jeffrey Dill-related!
					</h2>

					<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large' %>
				</div>

				<div class="transparent-soft-blue-box text-center" style="width: 466px; height: 350px; ">
					<h1 class="styled-h1">
						Welcome!
					</h1>

					<h2 class="styled-h2">
						Your #1 source for all things Jeffrey Dill-related!
					</h2>

					<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large' %>
				</div>

				<div class="transparent-soft-blue-box text-center" style="width: 466px; height: 350px; ">
					<h1 class="styled-h1">
						Welcome!
					</h1>

					<h2 class="styled-h2">
						Your #1 source for all things Jeffrey Dill-related!
					</h2>

					<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large' %>
				</div>

				<div class="transparent-soft-blue-box text-center" style="width: 466px; height: 350px; ">
					<h1 class="styled-h1">
						Welcome!
					</h1>

					<h2 class="styled-h2">
						Your #1 source for all things Jeffrey Dill-related!
					</h2>

					<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large' %>
				</div>

				<div class="transparent-soft-blue-box text-center" style="width: 466px; height: 350px; ">
					<h1 class="styled-h1">
						Welcome!
					</h1>

					<h2 class="styled-h2">
						Your #1 source for all things Jeffrey Dill-related!
					</h2>

					<%= link_to 'Come On In!', personal_pages_path, :class => 'btn btn-info btn-large' %>
				</div>
		    </div>
		</div>

		<!--////////////////////////////////////////////////////////
		////////////////////// BUTTON TO TRIGGER JAVASCRIPT FUNCTION
		/////////////////////////////////////////////////////////-->
		<%= link_to "Who Am I?...", "#", :onclick => "loadXMLDoc()", :class => "btn btn-info btn-medium" %>
	</body>
</html>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= provide(:title, 'Tweets') %>

		<script type="text/javascript">
			var imgorgH;
			var imgorgW;
			var modalON = false;
			var imgTitle;

			$(document).ready(function()
			{
				$(window).resize(function()
				{
					$('.loader').css(
					{
						'top': ($(window).height() - $('.loader').outerHeight()) / 2 + $(document).scrollTop(),
						'left': ($(window).width() - $('.loader').outerWidth()) / 2 + $(document).scrollLeft()
					});

					if (modalON)
					{
						$('.modal').css(
						{
							'top': ($(window).height() - $('.modal').outerHeight()) / 2 + $(document).scrollTop(),
							'left': ($(window).width() - $('.modal').outerWidth()) / 2 + $(document).scrollLeft()
						});
					}
				});
				
				$(".image").click(function()
				{     
					var clickedImg = $(this).find('img');
					imgTitle = $(this).next().text();
					var imgName = clickedImg.attr("alt");

					$(".loader").show();
					$(window).resize();

					if ($('.enlarged-img').attr('src'))
					{
						$('.enlarged-img').removeAttr('src');
					}
					
					$(".enlarged-img").attr("src", imgName);

					return false;
				});

				$(".enlarged-img").load(function()
				{
					$(".loader").hide();

					modalOpen(400);
					positionImg();

					var w = $(this).width();
					var h = $(this).height();

					$('.modal .image-title').text(imgTitle);
					$(".modal").css({'height': h, 'width': w});
					$(window).resize();  
				})
				.error(function()
				{ 
					alert("Can't Load image.");
				});

				function realSize()
				{
					var orgImg = $('.enlarged-img');
					var newImg = new Image();
					newImg.src = orgImg.attr('src');
					imgorgH = newImg.height;
					imgorgW = newImg.width;
				}

				function positionImg()
				{
					var newW;
					var newH;
			        
					realSize();

					var windowW = $(window).innerWidth();
					var windowH = $(window).innerHeight();
					var minHdiff = (windowW / 10) * 2;
					var minVdiff = (windowH / 10) * 2;
					var diffH = windowW - imgorgW;
					var diffV = windowH - imgorgH;

					if ((windowW - minHdiff) >= imgorgW)
					{
						newW = imgorgW;
					}
					else
					{
						newW = (windowW - minHdiff);
					}

					if ((windowH - minVdiff) >= imgorgH)
					{
						newH = imgorgH;
					}
					else
					{
						newH = (windowH - minVdiff);
					}

					$(".enlarged-img").css({"width": "auto", "height": "auto"});

					if (diffH <= minHdiff && diffV <= minVdiff)
					{
						if (diffH <= diffV)
						{
							$(".enlarged-img").css("width", newW);
						}
						else
						{
							$(".enlarged-img").css("height", newH);
						}
					}
					else
					{
						if (diffH <= minHdiff)
						{
							$(".enlarged-img").css("width", newW);
						}
						else
						{
							if (diffV <= minVdiff)
							{
								$(".enlarged-img").css("height", newH);
							}
						}
					}
				}

				$(".modal").hover(function()
				{
					$(".close").stop(true, true).fadeIn('fast');
				}
				,function()
				{
					$(".close").stop(true, true).fadeOut('fast');
				});

				$('.modal-bg').click(function()
				{
					modalClose(400);
				});

				$('.close').click(function()
				{
					modalClose(400);
					return false;
				});

				function modalOpen(delay)
				{
					modalON = true;
					$('.modal-bg').show();
					$('.modal-bg').stop().fadeIn(delay / 2);

					$('.modal').css(
					{
						'opacity': 0, 
						'display': 'block', 
						'margin-left': 'auto', 
						'margin-right': 'auto', 
						'margin-top': 'auto', 
						'margin-bottom': 'auto'
					});

					$('.modal').stop().delay(delay / 2).animate({'opacity': 1}, delay);
				}

				function modalClose(delay)
				{
					$('.modal').stop().fadeOut(delay / 2);
					$('.modal-bg').stop().delay(delay / 2).fadeOut(delay, function()
					{
						$('.modal').removeAttr('style');
						$('.modal-bg').removeAttr('style');
						modalON = false;
					});
				}
			});
		</script>
	</head>

	<div class="tweets-body">
		<% @tweets.each do |tweet| %>
			<div class="tweet-container span3 float">
				<div class="tweet-text">
					<%= tweet_text(tweet) %>
				</div>

				<br/>

				<ul class="gallery">
					<li>
						<%= link_to image_tag(tweet_url(tweet), :alt => tweet_url(tweet)), "", :class => "image" %>
					</li>
				</ul>
			</div>
		<% end %>
	</div>

	<div class="modal-bg"></div>
	
	<div class="modal">
		<a href="" class="close"></a>
		<img class="enlarged-img">
	</div>

	<span class="loader"><%= image_tag "loader.gif", :alt => "Loading..." %></span>
</html>